### ISSUE TITLE
The 0.4.1 release breaks on our systems

### ISSUE THREAD

**Issue by craigching** [sous-chefs/dpkg_autostart#21]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

The 0.4.1 release is broken on our chef 12.22.5 systems. 0.4.0 works fine.

## :pancakes: Cookbook version

0.4.1

## :woman_cook:  Chef-Infra Version

12.22.5

## :tophat: Platform details

```
# cat /etc/redhat-release
CentOS Linux release 7.8.2003 (Core)
```

## Steps To Reproduce

Sorry, not sure if I have good steps to reproduce, maybe with some guidance I could provide some, but I simply ran chef-client on one of our systems that downloaded the 0.4.1 version and got the following error:

```
Installing Cookbook Gems:
Compiling Cookbooks...
================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/dpkg_autostart/libraries/provider.rb
================================================================================
NoMethodError
-------------
undefined method `action' for Chef::Provider::DpkgAutostart:Class
Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/dpkg_autostart/libraries/provider.rb:13:in `<class:DpkgAutostart>'
  /var/chef/cache/cookbooks/dpkg_autostart/libraries/provider.rb:5:in `<class:Provider>'
  /var/chef/cache/cookbooks/dpkg_autostart/libraries/provider.rb:4:in `<class:Chef>'
  /var/chef/cache/cookbooks/dpkg_autostart/libraries/provider.rb:3:in `<top (required)>'
```

There is more output that I could provide if needed.

## :police_car: Expected behavior

I expected chef-client to finish with no errors.

**Comment by anetanel** [comment]
We are seeing the same issue.
chef 12.22.3
ubuntu 16.04
ruby 2.3.6p384 (2017-12-14 revision 61254)

**Comment by brightskylee** [comment]
same issue here.

**Comment by Idun0** [comment]
We are also seeing the same issue 
Chef: 12.19.36
Ubuntu: 16.04

**Comment by kategray** [comment]
Same issue, Amazon Linux 2.  Reverting to 0.4.0 fixes the issue.

**Comment by tasdikrahman** [comment]
Same issue with, ubuntu 16.04.2 LTS, reverting to 0.4.1, fixes. 
I tried fixing this here https://github.com/sous-chefs/dpkg_autostart/pull/25, please have a look. thanks
